// AUTO-GENERATED by pipeline.mjs — do not edit manually.
// (Empty template — pipeline.mjs regenerates this per project as scenes are added.)
import React from 'react';

const registry: Record<string, React.FC> = {};

export default registry;
