// AUTO-GENERATED by pipeline.mjs — do not edit manually.
import React from 'react';
import Scene_01 from './scenes/Scene_01';
import Scene_02 from './scenes/Scene_02';
import Scene_03 from './scenes/Scene_03';
import Scene_04 from './scenes/Scene_04';
import Scene_05 from './scenes/Scene_05';
import Scene_06 from './scenes/Scene_06';
import Scene_07 from './scenes/Scene_07';
import Scene_08 from './scenes/Scene_08';
import Scene_09 from './scenes/Scene_09';
import Scene_10 from './scenes/Scene_10';

const registry: Record<string, React.FC> = {
  'Scene01': Scene_01,
  'Scene02': Scene_02,
  'Scene03': Scene_03,
  'Scene04': Scene_04,
  'Scene05': Scene_05,
  'Scene06': Scene_06,
  'Scene07': Scene_07,
  'Scene08': Scene_08,
  'Scene09': Scene_09,
  'Scene10': Scene_10,
};

export default registry;
